const actions = {
    FETCH_TASK_LIST: 'FETCH_TASK_LIST',
    FETCH_TASK_LIST_SUCCESS: 'FETCH_TASK_LIST_SUCCESS',
    FETCH_TASK_LIST_FAILURE: 'FETCH_TASK_LIST_FAILURE',
    CREATE_AND_EDIT_TASK_MODAL: 'CREATE_AND_EDIT_TASK_MODAL',
    ADD_TASK: 'ADD_TASK',
    ADD_TASK_SUCCESS: 'ADD_TASK_SUCCESS',
    UPDATE_TASK_DETAILS: 'UPDATE_TASK_DETAILS',
    UPDATE_TASK_DETAILS_SUCCESS: 'UPDATE_TASK_DETAILS_SUCCESS',
    REMOVE_TASK: 'REMOVE_TASK',
    REMOVE_TASK_SUCCESS: 'REMOVE_TASK_SUCCESS',
};
  
export default actions;